// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmvN3Kyvs-YmjC2ZcA492N-siKlp5NEwY',
    appId: '1:770941042830:web:58bc8fe285b507e0ca49df',
    messagingSenderId: '770941042830',
    projectId: 'test-62ded',
    authDomain: 'test-62ded.firebaseapp.com',
    storageBucket: 'test-62ded.firebasestorage.app',
    measurementId: 'G-1D5NVVTV03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXonn2GN3EAiiokxzYtTJTUikpuLssKKA',
    appId: '1:770941042830:android:8edb220dd97ed5feca49df',
    messagingSenderId: '770941042830',
    projectId: 'test-62ded',
    storageBucket: 'test-62ded.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3eVStldWb-LXqLPxRwl1eGBVnEWTWmrQ',
    appId: '1:770941042830:ios:e192047a73e4019cca49df',
    messagingSenderId: '770941042830',
    projectId: 'test-62ded',
    storageBucket: 'test-62ded.firebasestorage.app',
    iosBundleId: 'com.example.arquiExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3eVStldWb-LXqLPxRwl1eGBVnEWTWmrQ',
    appId: '1:770941042830:ios:e192047a73e4019cca49df',
    messagingSenderId: '770941042830',
    projectId: 'test-62ded',
    storageBucket: 'test-62ded.firebasestorage.app',
    iosBundleId: 'com.example.arquiExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmvN3Kyvs-YmjC2ZcA492N-siKlp5NEwY',
    appId: '1:770941042830:web:16c33697a2a5e06aca49df',
    messagingSenderId: '770941042830',
    projectId: 'test-62ded',
    authDomain: 'test-62ded.firebaseapp.com',
    storageBucket: 'test-62ded.firebasestorage.app',
    measurementId: 'G-XRSYQWGQ5P',
  );
}
